# Generated by Django 5.0.2 on 2024-03-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название статьи",
                        max_length=150,
                        verbose_name="Заголовок",
                    ),
                ),
                ("slug", models.CharField(max_length=150, verbose_name="slug")),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Добавьте содержимое",
                        null=True,
                        verbose_name="Содержимое",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте изображение",
                        null=True,
                        upload_to="blog_foto",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "date_of_creation",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Признак публикации"
                    ),
                ),
                (
                    "view_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
                "ordering": ("date_of_creation", "is_published"),
            },
        ),
    ]
